# ExaBGP — Simulasi ISP-2 (ISP Komersial Backup)
# AS 65101 | Peer: border-2 100.64.0.10
# Inject: prefix ISP Indonesia + CDN (sebagai backup/secondary commercial ISP)

neighbor 100.64.0.10 {
  router-id 100.64.0.9;
  local-address 100.64.0.9;
  local-as 65101;
  peer-as 65010;

  family {
    ipv4 unicast;
  }

  static {
    # === Indosat Ooredoo (AS4761) ===
    route 114.0.0.0/14     { next-hop 100.64.0.9; as-path [4761]; }
    route 36.82.0.0/16     { next-hop 100.64.0.9; as-path [4761]; }
    route 114.121.0.0/16   { next-hop 100.64.0.9; as-path [4761]; }
    route 202.62.0.0/18    { next-hop 100.64.0.9; as-path [4761]; }

    # === XL Axiata (AS24203) ===
    route 111.92.0.0/16    { next-hop 100.64.0.9; as-path [24203]; }
    route 36.77.0.0/16     { next-hop 100.64.0.9; as-path [24203]; }
    route 36.78.0.0/16     { next-hop 100.64.0.9; as-path [24203]; }

    # === Smartfren (AS9541) ===
    route 103.247.96.0/22  { next-hop 100.64.0.9; as-path [9541]; }
    route 118.98.0.0/15    { next-hop 100.64.0.9; as-path [9541]; }

    # === MyRepublic Indonesia (AS133949) ===
    route 103.26.20.0/22   { next-hop 100.64.0.9; as-path [133949]; }

    # === Google LLC (AS15169) — via ISP-2 ===
    route 8.8.8.0/24       { next-hop 100.64.0.9; as-path [4761 15169]; }
    route 8.8.4.0/24       { next-hop 100.64.0.9; as-path [4761 15169]; }
    route 142.250.0.0/15   { next-hop 100.64.0.9; as-path [4761 15169]; }

    # === Cloudflare (AS13335) — via ISP-2 ===
    route 1.1.1.0/24       { next-hop 100.64.0.9; as-path [4761 13335]; }
    route 1.0.0.0/24       { next-hop 100.64.0.9; as-path [4761 13335]; }
    route 104.16.0.0/13    { next-hop 100.64.0.9; as-path [4761 13335]; }

    # === Meta/Facebook (AS32934) — via ISP-2 ===
    route 157.240.0.0/16   { next-hop 100.64.0.9; as-path [4761 32934]; }

    # === Amazon AWS (AS16509) — via ISP-2 ===
    route 13.228.0.0/15    { next-hop 100.64.0.9; as-path [4761 16509]; }
    route 52.94.0.0/22     { next-hop 100.64.0.9; as-path [4761 16509]; }

    # === Prefix IDREN via ISP-2 (AS-path lebih panjang dari ISP-1) ===
    route 152.118.0.0/16   { next-hop 100.64.0.9; as-path [4761 7713 23700 7642]; }
    route 167.205.0.0/16   { next-hop 100.64.0.9; as-path [4761 7713 23700 7654]; }

    # === ISP-2 sendiri — prefix unik ===
    route 100.122.0.0/16   { next-hop 100.64.0.9; as-path [65101]; }

    # === Overlap prefix — tersedia via ISP-1 dan ISP-2 (demo local-pref LAB-04) ===
    route 100.121.0.0/16   { next-hop 100.64.0.9; as-path [65101]; }
  }
}
