frr defaults traditional
hostname frr-isp2
!
router bgp 65101
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.9
 neighbor 100.64.0.10 remote-as 65010
 neighbor 100.64.0.10 description "UMM border-2"
 neighbor 100.64.2.10 remote-as 65101
 neighbor 100.64.2.10 description "ExaBGP route injector"
 !
 address-family ipv4 unicast
  neighbor 100.64.0.10 activate
  neighbor 100.64.0.10 next-hop-self
  neighbor 100.64.2.10 activate
  neighbor 100.64.2.10 soft-reconfiguration inbound
 exit-address-family
!
