frr defaults traditional
hostname idren-pop
!
ip route 100.68.0.0/16 Null0
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.1
 neighbor 100.64.0.2 remote-as 65010
 neighbor 100.64.0.2 description UMM-Border
 !
 address-family ipv4 unicast
  network 100.68.0.0/16
 exit-address-family
!
