frr defaults traditional
hostname idren-pop
!
ip route 100.68.0.0/16 Null0
!
! BUG #3: route-map BLOCK-INBOUND memblokir semua prefix dari umm-border
ip prefix-list BLOCK-ALL seq 10 deny any
!
route-map BLOCK-INBOUND permit 10
 match ip address prefix-list BLOCK-ALL
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.1
 neighbor 100.64.0.2 remote-as 65010
 neighbor 100.64.0.2 description Border-UMM
 !
 address-family ipv4 unicast
  network 100.68.0.0/16
  neighbor 100.64.0.2 activate
  neighbor 100.64.0.2 soft-reconfiguration inbound
  neighbor 100.64.0.2 route-map BLOCK-INBOUND in
 exit-address-family
!
