frr defaults traditional
hostname umm-border
!
! BUG #2: intentionally NO ip route 100.68.1.0/24 blackhole
!         network statement tidak akan diiklankan
!
router bgp 65010
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.2
 ! BUG #1: remote-as salah — seharusnya 65000
 neighbor 100.64.0.1 remote-as 65099
 neighbor 100.64.0.1 description IDREN-PoP
 !
 address-family ipv4 unicast
  network 100.68.1.0/24
  neighbor 100.64.0.1 activate
 exit-address-family
!
