frr version 8.4_git
frr defaults traditional
hostname border-2
no ipv6 forwarding
!
ip route 100.72.1.0/24 Null0
ip route 100.72.2.0/24 Null0
ip route 100.64.1.1/32 100.64.0.17
!
router bgp 65010
 bgp router-id 100.64.1.2
 no bgp ebgp-requires-policy
 neighbor 100.64.0.9 remote-as 65101
 neighbor 100.64.0.9 description "ISP-2"
 neighbor 100.64.0.13 remote-as 65200
 neighbor 100.64.0.13 description "IIX"
 neighbor 100.64.1.1 remote-as 65010
 neighbor 100.64.1.1 description "iBGP ke border-1"
 neighbor 100.64.1.1 update-source lo
 !
 address-family ipv4 unicast
  network 100.72.1.0/24
  network 100.72.2.0/24
  neighbor 100.64.0.9 soft-reconfiguration inbound
  neighbor 100.64.0.9 route-map IMPORT-FROM-ISP2 in
  neighbor 100.64.0.9 route-map EXPORT-TO-ISP2 out
  neighbor 100.64.0.13 soft-reconfiguration inbound
  neighbor 100.64.0.13 route-map IMPORT-FROM-IIX in
  neighbor 100.64.0.13 route-map EXPORT-TO-IIX out
  neighbor 100.64.1.1 next-hop-self
  neighbor 100.64.1.1 soft-reconfiguration inbound
 exit-address-family
exit
!
ip prefix-list OWN-PREFIX seq 10 permit 100.72.1.0/24
ip prefix-list OWN-PREFIX seq 20 permit 100.72.2.0/24
ip prefix-list OWN-PREFIX seq 99 deny any
!
route-map EXPORT-UPSTREAM permit 10
 match ip address prefix-list OWN-PREFIX
exit
!
route-map IMPORT-FROM-ISP2 permit 10
 set local-preference 100
exit
!
route-map IMPORT-FROM-IIX permit 10
 set local-preference 200
exit
!
route-map EXPORT-TO-IIX permit 10
 match ip address prefix-list OWN-PREFIX
 set as-path prepend 65010
exit
!
route-map EXPORT-TO-ISP2 permit 10
 match ip address prefix-list OWN-PREFIX
 set as-path prepend 65010 65010
exit
!
