frr defaults traditional
hostname frr-isp1
!
router bgp 65100
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.5
 neighbor 100.64.0.6 remote-as 65010
 neighbor 100.64.0.6 description "UMM border-1"
 neighbor 100.64.2.6 remote-as 65100
 neighbor 100.64.2.6 description "ExaBGP route injector"
 !
 address-family ipv4 unicast
  neighbor 100.64.0.6 activate
  neighbor 100.64.0.6 next-hop-self
  neighbor 100.64.2.6 activate
  neighbor 100.64.2.6 soft-reconfiguration inbound
 exit-address-family
!
