frr version 8.4_git
frr defaults traditional
hostname border-1
no ipv6 forwarding
!
ip route 100.72.1.0/24 Null0
ip route 100.72.2.0/24 Null0
ip route 100.64.1.2/32 100.64.0.18
!
router bgp 65010
 bgp router-id 100.64.1.1
 no bgp ebgp-requires-policy
 neighbor 100.64.0.1 remote-as 65000
 neighbor 100.64.0.1 description "IDREN PoP"
 neighbor 100.64.0.5 remote-as 65100
 neighbor 100.64.0.5 description "ISP-1"
 neighbor 100.64.1.2 remote-as 65010
 neighbor 100.64.1.2 description "iBGP ke border-2"
 neighbor 100.64.1.2 update-source lo
 !
 address-family ipv4 unicast
  network 100.72.1.0/24
  network 100.72.2.0/24
  neighbor 100.64.0.1 soft-reconfiguration inbound
  neighbor 100.64.0.1 route-map IMPORT-FROM-IDREN in
  neighbor 100.64.0.1 route-map EXPORT-TO-IDREN out
  neighbor 100.64.0.5 soft-reconfiguration inbound
  neighbor 100.64.0.5 route-map IMPORT-FROM-ISP1 in
  neighbor 100.64.0.5 route-map EXPORT-TO-ISP1 out
  neighbor 100.64.1.2 next-hop-self
 exit-address-family
exit
!
ip prefix-list OWN-PREFIX seq 10 permit 100.72.1.0/24
ip prefix-list OWN-PREFIX seq 20 permit 100.72.2.0/24
ip prefix-list OWN-PREFIX seq 99 deny any
!
bgp as-path access-list UNIV-ID-DIRECT seq 5 permit ^65000 (7642|7654|24855|45166|45974|45958|45997)$
!
route-map EXPORT-UPSTREAM permit 10
 match ip address prefix-list OWN-PREFIX
exit
!
route-map IMPORT-FROM-IDREN permit 10
 match as-path UNIV-ID-DIRECT
 set local-preference 350
exit
!
route-map IMPORT-FROM-IDREN permit 20
 set local-preference 300
exit
!
route-map IMPORT-FROM-ISP1 permit 10
 set local-preference 150
exit
!
route-map EXPORT-TO-IDREN permit 10
 match ip address prefix-list OWN-PREFIX
exit
!
route-map EXPORT-TO-ISP1 permit 10
 match ip address prefix-list OWN-PREFIX
 set as-path prepend 65010
exit
!
