frr defaults traditional
hostname frr-iix
!
router bgp 65200
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.13
 neighbor 100.64.0.14 remote-as 65010
 neighbor 100.64.0.14 description "UMM border-2"
 neighbor 100.64.2.14 remote-as 65200
 neighbor 100.64.2.14 description "ExaBGP route injector"
 !
 address-family ipv4 unicast
  neighbor 100.64.0.14 activate
  neighbor 100.64.0.14 next-hop-self
  neighbor 100.64.2.14 activate
  neighbor 100.64.2.14 soft-reconfiguration inbound
 exit-address-family
!
