frr defaults traditional
hostname frr-idren
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.1
 neighbor 100.64.0.2 remote-as 65010
 neighbor 100.64.0.2 description "UMM border-1"
 neighbor 100.64.2.2 remote-as 65000
 neighbor 100.64.2.2 description "ExaBGP route injector"
 !
 address-family ipv4 unicast
  neighbor 100.64.0.2 activate
  neighbor 100.64.0.2 next-hop-self
  neighbor 100.64.2.2 activate
  neighbor 100.64.2.2 soft-reconfiguration inbound
 exit-address-family
!
